### ISSUE TITLE
docker.credentials.errors.InitializationError: docker-credential-gcloud not installed or not available in PATH

### ISSUE THREAD

**Issue by twogood** [docker-snap/docker-snap#19] opened 2021-01-10 20:45 UTC
As part of one of my Docker workflows I need to push an image to Google Container Registry (gcr). To authenticated with the GCR, Docker must be allowed to call `docker-credential-gcloud` that for example can be found in the `google-cloud-sdk` snap.

It seems like this issue is very similar to #10 but I file a separate issue with the error message I get.

More info:

I have created a subdirectory `~/snap/docker/current/.docker/`

I have made `~/.docker/` a symlink to `~/snap/docker/current/.docker/`

Those are releated to #12 and #18.

Then I have performed the instructions at https://cloud.google.com/container-registry/docs/advanced-authentication#gcloud-helper to run `gcloud auth configure-docker` so that my `~/.docker/config.json`  looks like this:

```
{
  "credHelpers": {
    "eu.gcr.io": "gcloud"
  }
}
```

When I run `docker-compose push` I get this error:

```
WARNING: Some services (web) use the 'deploy' key, which will be ignored. Compose does not support 'deploy' configuration - use `docker stack deploy` to deploy to a swarm.
Pushing web (eu.gcr.io/*******************)...
Traceback (most recent call last):
  File "/snap/docker/471/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.25.5', 'console_scripts', 'docker-compose')()
  File "/snap/docker/471/lib/python3.5/site-packages/compose/cli/main.py", line 72, in main
    command()
  File "/snap/docker/471/lib/python3.5/site-packages/compose/cli/main.py", line 128, in perform_command
    handler(command, command_options)
  File "/snap/docker/471/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/snap/docker/471/lib/python3.5/site-packages/compose/cli/errors.py", line 45, in handle_connection_errors
    yield
  File "/snap/docker/471/lib/python3.5/site-packages/compose/cli/main.py", line 128, in perform_command
    handler(command, command_options)
  File "/snap/docker/471/lib/python3.5/site-packages/compose/cli/main.py", line 761, in push
    ignore_push_failures=options.get('--ignore-push-failures')
  File "/snap/docker/471/lib/python3.5/site-packages/compose/project.py", line 699, in push
    service.push(ignore_push_failures)
  File "/snap/docker/471/lib/python3.5/site-packages/compose/service.py", line 1259, in push
    output = self.client.push(repo, tag=tag, stream=True)
  File "/snap/docker/471/lib/python3.5/site-packages/docker/api/image.py", line 465, in push
    header = auth.get_config_header(self, registry)
  File "/snap/docker/471/lib/python3.5/site-packages/docker/auth.py", line 48, in get_config_header
    client._auth_configs, registry, credstore_env=client.credstore_env
  File "/snap/docker/471/lib/python3.5/site-packages/docker/auth.py", line 324, in resolve_authconfig
    return authconfig.resolve_authconfig(registry)
  File "/snap/docker/471/lib/python3.5/site-packages/docker/auth.py", line 235, in resolve_authconfig
    cfg = self._resolve_authconfig_credstore(registry, store_name)
  File "/snap/docker/471/lib/python3.5/site-packages/docker/auth.py", line 262, in _resolve_authconfig_credstore
    store = self._get_store_instance(credstore_name)
  File "/snap/docker/471/lib/python3.5/site-packages/docker/auth.py", line 287, in _get_store_instance
    name, environment=self._credstore_env
  File "/snap/docker/471/lib/python3.5/site-packages/docker/credentials/store.py", line 25, in __init__
    self.program
docker.credentials.errors.InitializationError: docker-credential-gcloud not installed or not available in PATH
```

**Comment by tianon** [comment] 2021-01-11 18:54
As you've noted, #10 is where we are tracking supporting credential helpers (even though your error message is slightly different).  We do not support them today.

(Closing this as a duplicate of #10 to keep the conversation in one place :pray:)

**Closed by tianon** 2021-01-11 18:54 UTC
