### ISSUE TITLE
sysctl command not allowed in host network namespace: unknown

### ISSUE THREAD

**Issue by snowsky** [docker-snap/docker-snap#40] opened 2021-06-04 19:57 UTC
Hi there,

We run into an issue with docker on `latest/edge` channel. A sysctl command will run in the container using host network. Here is the API log from Docker:

```
msg="Handler for POST /containers/8483159eeddf0962ea101db60eb26b787a2498147ab494cb2da96c9b289bff9d/start returned error: OCI runtime create failed: sysctl xxxx not allowed in host network namespace: unknown"
```

This issue was resolved after we installed docker from `latest/stable` channel.

The current versions of Docker snap:
- latest/edge: 19.03.13
- latest/edge: 20.10.6

Thanks,
Hao

**Comment by snowsky** [comment] 2021-06-04 20:06
May add more contexts from logs before hitting the `unknown` error:

```
  3 msg="starting signal loop" namespace=moby path=/run/snap.docker/containerd/daemon/io.containerd.runtime.v2.task/moby/be3637046c8df9b8daa69169df5a2e29a1abbf5e2b656aabd63d406aae310fb2 pid=562
  2 msg="copy shim log" error="read /proc/self/fd/12: file already closed"
  1 msg="stream copy error: reading from a closed fifo"
4   msg="stream copy error: reading from a closed fifo"
  1 msg="be3637046c8df9b8daa69169df5a2e29a1abbf5e2b656aabd63d406aae310fb2 cleanup: failed to delete container from containerd: no such container"
  2 msg="Handler for POST /containers/be3637046c8df9b8daa69169df5a2e29a1abbf5e2b656aabd63d406aae310fb2/start returned error: OCI runtime create failed: sysctl xxxx not allowed in host network namespace: unknown"
```

**Comment by tianon** [comment] 2021-06-04 23:41
This looks like you've filtered part of the error message -- can you give us an example command to reproduce?

It sounds like you were probably taking advantage of https://github.com/opencontainers/runc/issues/2693 which was fixed in https://github.com/opencontainers/runc/pull/2706, so this is likely going to be an unfortunate case of "now it works as it should've all along"

**Comment by snowsky** [comment] 2021-06-07 14:49
Hi @tianon, we got the errors from Docker API. It seems it is a new issue, https://github.com/moby/moby/issues/28821#issuecomment-814208448. We are using the version of Ubuntu docker snap, 20.10.6 916, on latest/beta channel.

**Comment by snowsky** [comment] 2021-06-07 14:55
It seems this is the new bug, https://github.com/moby/moby/issues/42288.

**Comment by tianon** [comment] 2021-06-07 16:34
Ah!  In that case, once the GitHub Actions on https://github.com/docker-snap/docker-snap/pull/41 finish, there'll be a `docker.snap` artifact you can download and test to verify it fixes your issue.

**Closed** 2021-06-07 19:54 UTC
